'use client'

import React, { useState } from 'react'
import { LineChart, Line, ResponsiveContainer } from 'recharts'
import styles from './ai.module.css'

export default function AIReportCard({
  report,
  loading = false,
  onGenerateReport,
}) {
  const [period, setPeriod] = useState('weekly')

  if (loading) {
    return (
      <div className={styles.card}>
        <div className={styles.cardHeader}>
          <div className={styles.titleGroup}>
            <span className={styles.aiBadge}>✨ AI Report</span>
            <h3 className={styles.cardTitle}>Executive Health Narrative</h3>
          </div>
        </div>
        <div className={styles.skeleton} style={{ height: 40, width: '60%', marginBottom: 16 }} />
        <div style={{ display: 'grid', gridTemplateColumns: 'repeat(3, 1fr)', gap: 12, marginBottom: 16 }}>
          <div className={styles.skeleton} style={{ height: 80 }} />
          <div className={styles.skeleton} style={{ height: 80 }} />
          <div className={styles.skeleton} style={{ height: 80 }} />
        </div>
        <div className={styles.skeleton} style={{ height: 100, width: '100%' }} />
      </div>
    )
  }

  if (!report) {
    return (
      <div className={styles.card}>
        <div className={styles.cardHeader}>
          <div className={styles.titleGroup}>
            <span className={styles.aiBadge}>✨ AI Report</span>
            <h3 className={styles.cardTitle}>Executive Health Narrative</h3>
          </div>
          {onGenerateReport && (
            <button className={styles.actionBtn} onClick={() => onGenerateReport(period)}>
              <span>✨ Generate Report</span>
            </button>
          )}
        </div>
        <div style={{ padding: '32px 16px', textAlign: 'center', color: 'var(--text-secondary)' }}>
          <div style={{ fontSize: 28, marginBottom: 8 }}>📄</div>
          <div style={{ fontSize: 14, fontWeight: 700, color: 'var(--text-primary)' }}>
            No Executive Report Generated Yet
          </div>
          <p style={{ fontSize: 12, margin: '6px auto 16px', maxWidth: 460, color: 'var(--text-secondary)' }}>
            Generate a verified health and safety appraisal synthesized from actual historical telemetry sent by the ESP32 hardware node.
          </p>
          {onGenerateReport && (
            <button
              onClick={() => onGenerateReport(period)}
              style={{
                backgroundColor: 'var(--accent-primary)',
                color: '#000',
                border: 'none',
                padding: '8px 16px',
                borderRadius: 8,
                fontSize: 12,
                fontWeight: 700,
                cursor: 'pointer',
              }}
            >
              Generate {period.charAt(0).toUpperCase() + period.slice(1)} Report Now
            </button>
          )}
        </div>
      </div>
    )
  }

  const headline = report.headlineStat || report.title || 'Telemetry Analysis Completed'
  const narrative = report.narrative || report.executiveSummary || report.healthAssessment || 'Health evaluation complete.'
  const grade = report.grade || '--'
  const stats = report.stats || {}
  const sparklines = report.sparklines || { voltage: [], temperature: [] }

  const handleDownload = () => {
    const textContent = `# Battery Vital Health Report (${period.toUpperCase()})
Date: ${new Date().toLocaleDateString()}
Grade: ${grade}
Headline: ${headline}

## Executive Summary
${narrative}

## Aggregated Operating Stats
- Average Voltage: ${stats.avgVoltage != null ? `${stats.avgVoltage} V` : 'N/A'}
- Max Temperature: ${stats.maxTemp != null ? `${stats.maxTemp} °C` : 'N/A'}
- Gas Alerts Count: ${stats.gasExposures ?? 0}
- Cumulative Throughput: ${stats.throughputAh != null ? `${stats.throughputAh} Ah` : 'N/A'}
- Evaluated Samples: ${stats.samples != null ? stats.samples : 'Recorded telemetry'}

---
Generated by Battery Vital Multi-Model AI Engine.
`
    const blob = new Blob([textContent], { type: 'text/markdown' })
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url
    a.download = `battery_health_report_${period}_${Date.now()}.md`
    a.click()
    URL.revokeObjectURL(url)
  }

  return (
    <div className={styles.card}>
      {/* Header */}
      <div className={styles.cardHeader}>
        <div className={styles.titleGroup}>
          <span className={styles.aiBadge}>✨ AI Report</span>
          <h3 className={styles.cardTitle}>Executive Health Narrative</h3>
        </div>
        <div className={styles.headerActions}>
          <select
            value={period}
            onChange={(e) => {
              setPeriod(e.target.value)
              if (onGenerateReport) onGenerateReport(e.target.value)
            }}
            className={styles.actionBtn}
            style={{ padding: '4px 8px' }}
          >
            <option value="weekly">Weekly Period</option>
            <option value="monthly">Monthly Period</option>
          </select>
          <button className={styles.actionBtn} onClick={handleDownload} title="Export Markdown Report">
            📥 Export Report
          </button>
        </div>
      </div>

      {/* Magazine-Style Top Row: Headline + Grade */}
      <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start', marginBottom: 20 }}>
        <div style={{ flex: 1, paddingRight: 16 }}>
          <div style={{ fontSize: 11, textTransform: 'uppercase', color: 'var(--text-tertiary, #4E5A6B)', fontWeight: 700, letterSpacing: '0.04em', marginBottom: 4 }}>
            Period Key Finding
          </div>
          <h2 style={{ margin: 0, fontSize: 20, fontWeight: 700, color: 'var(--text-primary, #F0F4F8)', lineHeight: 1.3 }}>
            {headline}
          </h2>
        </div>

        <div
          style={{
            display: 'flex',
            flexDirection: 'column',
            alignItems: 'center',
            justifyContent: 'center',
            width: 56,
            height: 56,
            background: 'rgba(0, 232, 160, 0.1)',
            border: '2px solid var(--accent-primary, #00E8A0)',
            borderRadius: 12,
            flexShrink: 0,
          }}
        >
          <span style={{ fontSize: 10, color: 'var(--text-tertiary, #4E5A6B)', fontWeight: 700 }}>GRADE</span>
          <span style={{ fontSize: 18, fontWeight: 900, color: 'var(--accent-primary, #00E8A0)' }}>{grade}</span>
        </div>
      </div>

      {/* 3 Mini Sparkline Cards */}
      <div style={{ display: 'grid', gridTemplateColumns: 'repeat(3, 1fr)', gap: 12, marginBottom: 20 }}>
        {/* Voltage Stability */}
        <div style={{ background: 'var(--bg-surface-raised)', border: '1px solid var(--border)', borderRadius: 10, padding: 12 }}>
          <div style={{ display: 'flex', justifyContent: 'space-between', fontSize: 11, color: 'var(--text-secondary)', marginBottom: 4 }}>
            <span>⚡ Voltage Stability</span>
            <strong style={{ color: '#00E8A0' }}>{stats.avgVoltage ? `${stats.avgVoltage}V` : 'Normal'}</strong>
          </div>
          <div style={{ width: '100%', height: 36 }}>
            <ResponsiveContainer width="100%" height="100%">
              <LineChart data={sparklines.voltage}>
                <Line type="monotone" dataKey="v" stroke="#00E8A0" strokeWidth={2} dot={false} isAnimationActive={false} />
              </LineChart>
            </ResponsiveContainer>
          </div>
        </div>

        {/* Thermal Events */}
        <div style={{ background: 'var(--bg-surface-raised)', border: '1px solid var(--border)', borderRadius: 10, padding: 12 }}>
          <div style={{ display: 'flex', justifyContent: 'space-between', fontSize: 11, color: 'var(--text-secondary)', marginBottom: 4 }}>
            <span>🌡️ Thermal Peak</span>
            <strong style={{ color: (stats.maxTemp || 25) > 40 ? '#FF2D55' : '#38BDF8' }}>
              {stats.maxTemp ? `${stats.maxTemp}°C` : '26°C'}
            </strong>
          </div>
          <div style={{ width: '100%', height: 36 }}>
            <ResponsiveContainer width="100%" height="100%">
              <LineChart data={sparklines.temperature}>
                <Line type="monotone" dataKey="v" stroke="#38BDF8" strokeWidth={2} dot={false} isAnimationActive={false} />
              </LineChart>
            </ResponsiveContainer>
          </div>
        </div>

        {/* Gas Exposures */}
        <div style={{ background: 'var(--bg-surface-raised)', border: '1px solid var(--border)', borderRadius: 10, padding: 12 }}>
          <div style={{ display: 'flex', justifyContent: 'space-between', fontSize: 11, color: 'var(--text-secondary)', marginBottom: 4 }}>
            <span>💨 Gas Excursions</span>
            <strong style={{ color: stats.gasExposures > 0 ? '#FF6B35' : '#00E8A0' }}>
              {stats.gasExposures ?? 0} Events
            </strong>
          </div>
          <div style={{ marginTop: 8, fontSize: 11, color: 'var(--text-tertiary)' }}>
            MQ-2 / MQ-135 Baseline Clean
          </div>
        </div>
      </div>

      {/* Narrative Paragraph */}
      <div style={{ background: 'var(--bg-surface-raised)', border: '1px solid var(--border)', borderRadius: 10, padding: 14 }}>
        <div style={{ fontSize: 11, textTransform: 'uppercase', letterSpacing: '0.04em', color: 'var(--text-tertiary)', fontWeight: 700, marginBottom: 6 }}>
          Detailed Executive Analysis
        </div>
        <p style={{ margin: 0, fontSize: 13, color: 'var(--text-secondary)', lineHeight: 1.55 }}>
          {narrative}
        </p>
      </div>
    </div>
  )
}
