const mongoose = require('mongoose');

const alertSchema = new mongoose.Schema({
  batteryId: { type: String, required: true },
  deviceId: { type: mongoose.Schema.Types.ObjectId, ref: 'Device' },
  timestamp: { type: Date, default: Date.now },
  severity: { type: String, enum: ['SAFE', 'CAUTION', 'WARNING', 'CRITICAL', 'EMERGENCY'], required: true },
  type: { type: String, enum: ['THERMAL', 'GAS', 'VOLTAGE', 'CURRENT', 'SYSTEM', 'SAFETY_STATE', 'PREDICTION'] },
  message: { type: String, required: true },
  bhi: Number,
  sensorData: {
    voltage: Number,
    current: Number,
    temperature: Number,
    gasIndex: Number,
    soc: Number
  },
  acknowledged: { type: Boolean, default: false },
  acknowledgedBy: String,
  acknowledgedAt: Date,
  autoGenerated: { type: Boolean, default: true }
}, { collection: 'alerts' });

alertSchema.index({ batteryId: 1, severity: 1, timestamp: -1 });
alertSchema.index({ timestamp: -1 });
alertSchema.index({ acknowledged: 1 });

module.exports = mongoose.model('Alert', alertSchema);
